// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASWGFMQKIyWEsrQKGSdLCd-GEOgisTRmM',
    appId: '1:380196657706:web:5f87b1adaa430d33710153',
    messagingSenderId: '380196657706',
    projectId: 'practical-practice-b0468',
    authDomain: 'practical-practice-b0468.firebaseapp.com',
    storageBucket: 'practical-practice-b0468.appspot.com',
    measurementId: 'G-CH7BYRX8KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBy-zomJJ7vFRciP3t7efSdqS8p3gLuwc',
    appId: '1:380196657706:android:d4c37cc15cec97da710153',
    messagingSenderId: '380196657706',
    projectId: 'practical-practice-b0468',
    storageBucket: 'practical-practice-b0468.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgMJXicjECOfKkOxMIA2CIAYvGdgKMxSY',
    appId: '1:380196657706:ios:38effca84f64d26a710153',
    messagingSenderId: '380196657706',
    projectId: 'practical-practice-b0468',
    storageBucket: 'practical-practice-b0468.appspot.com',
    iosBundleId: 'com.example.testPracticeTwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgMJXicjECOfKkOxMIA2CIAYvGdgKMxSY',
    appId: '1:380196657706:ios:c95e022f9033e81b710153',
    messagingSenderId: '380196657706',
    projectId: 'practical-practice-b0468',
    storageBucket: 'practical-practice-b0468.appspot.com',
    iosBundleId: 'com.example.testPracticeTwo.RunnerTests',
  );
}
